name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ''

    - name: Clean Flutter build
      run: flutter clean

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web

    - name: Deploy to Netlify
      run: netlify deploy --prod --dir=build/web --site=$NETLIFY_SITE_ID
      env:
        NETLIFY_AUTH_TOKEN: nfp_xzcmJohsEctijYHiCQ1WyobbyXU78bNx0177
        NETLIFY_SITE_ID: 5521f33d-2eca-4d82-8962-263707be996e
 
